language: python
matrix:
  include:
    #- python: 3.6
    - python: 3.7

    - os: linux
      dist: xenial
      sudo: true

    - os: osx
      dist: xcode11

    - os: windows

notifications:
  # send notifications only on master failure
  email:
    only: master
cache: pip
# install dependencies
install:
  - travis_wait pip install -e .
before_script: cd tests/ci_tests
# run tests
script:
        - python3 full_test.py
