language: python
matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true

    - os: osx
      python: 3.6
      dist: xcode11
      osx_image: xcode11

#    - os: windows
#      python: 3.7

notifications:
  # send notifications only on master failure
  email:
    only: master
cache: pip
# install dependencies
install:
  - travis_wait pip install -e .
before_script: cd tests/ci_tests
# run tests
script:
        - python3 full_test.py
