language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true 
cache: pip
# install dependencies
install:
  - pip install mindsdb
# run tests
before_script: cd mindsdb
script:
  - pytest