version: "3"

services:

  mindsdb:
    image: "mindsdb/mindsdb"
    restart: always
    ports:
      - '47334:47334'
      - '47335:47335'
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:47334/ping"]
      interval: 5s
      timeout: 4s
      retries: 100


  mysql_db:
    image: "mindsdb/mysql-handler-test"
    ports:
      - 3307:3306
    command: --secure-file-priv=/
    environment:
      MYSQL_ROOT_PASSWORD: "supersecret"
      MYSQL_DATABASE: "test"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 5s
      timeout: 4s
      retries: 100


  db_handler:
    image: "db_handler"
    environment:
      - 'PARAMS={"connection_data": {"host": "mysql_db", "port": "3306", "user": "root", "password": "supersecret", "database": "test", "ssl": false}, "name": "foo", "type": "mysql"}'

    ports:
      - 5000:5000
    depends_on:
      - mindsdb
      - mysql_db

    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 5s
      timeout: 4s
      retries: 100
