[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "MindsDB"
dynamic = ["version"]
description = "MindsDB server, provides server capabilities to mindsdb native python library"
readme = "README.md"
license = "GPL-3.0"
requires-python = ">=3.7"
authors = [
    { name = "MindsDB Inc", email = "jorge@mindsdb.com" },
]
keywords = [
    "pdf",
    "reference",
    "linkrot",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "lightwood >= 22.9.1.0, < 22.9.2.0",
    "markupsafe == 2.0.1",
    "flask-restx >= 0.2.0",
    "flask >= 1.0, < 2.0",
    "python-multipart >= 0.0.5",
    "pyparsing == 2.3.1",
    "cryptography>=35.0",
    "psycopg[binary] >= 1.15.3",
    "python-tds >= 1.10.0",
    "waitress >= 1.4.4",
    "pymongo[srv] >= 4.1.1",
    "psutil",
    "sqlalchemy >= 1.3.0",
    "alembic >= 1.3.3",
    "sentry-sdk",
    "walrus==0.8.2",
    "flask-compress >= 1.0.0",
    "kafka-python >= 2.0.0",
    "appdirs >= 1.0.0",
    "mindsdb-sql >= 0.4.2",
    "checksumdir >= 1.2.0",
    "mindsdb-streams == 0.1.1",
    "duckdb == 0.4.0",
    "requests >= 2.0.0",
    "mysql-connector-python",
    "clickhouse-driver",
    "charset-normalizer",
    "dill >= 0.3.4",
    "pyOpenSSL >= 22.0.0",
    "pydateinfer==0.3.0",
    "build==0.8.0",
]

[project.optional-dependencies]
test = [
    "docker >= 5.0.3",
    "netifaces >= 0.11.0",
    "mysql-connector-python==8.0.29",
    "pytest",
]

[project.urls]
homepage = "https://pypi.org/project/mindsdb/"
repository = "https://github.com/mindsdb/mindsdb"

[tool.hatch.version]
path = "mindsdb/__about__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/mindsdb",
]

[tool.hatch.build.targets.wheel]
packages = [
    "/mindsdb",
]
