name: 🐞 Bug report
description: Create a bug report to help us improve Milvus
title: "[Bug]: "

  
body:
- type: markdown
  value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If y
