name: 🐞 Bug report
description: Create a bug report to help us improve Milvus
title: "[Bug]: "

body:
- type: dropdown
  id: download
  attributes:
    label: How did you download the software?
    options:
      - Homebrew
      - MacPorts
      - apt-get
      - Built from source
  validations:
    required: true
