---
version: "3.2"

services:
  mindsdb-migrations:
    image: mindsdb/mindsdb_trial:latest
    command: bash -c "cd /mindsdb && python ./mindsdb/migrations/migrate.py"
    environment:
      MINDSDB_STORAGE_DIR: "/storage/var"
    volumes:
      - type: bind
        source: .
        target: /storage

  mindsdb-core:
    image: mindsdb/mindsdb_trial:latest
    restart: always
    ports:
      - "47334:47334"
      - "47335:47335"
    command: bash -c "cd /mindsdb && python -m mindsdb"
    environment:
      MINDSDB_EXECUTOR_SERVICE: "True"
      MINDSDB_EXECUTOR_HOSTNAME: "executor-service"
      MINDSDB_EXECUTOR_PORT: 5002
      MINDSDB_ML_SERVICE_HOST: "ml-service"
      MINDSDB_ML_SERVICE_PORT: 5001
      MINDSDB_DB_SERVICE_HOST: "db-service"
      MINDSDB_DB_SERVICE_PORT: 5000
      MINDSDB_DOCKER_ENV: "True"
      MINDSDB_STORAGE_DIR: "${MINDSDB_STORAGE_DIR:/storage/var}"
      FLASK_DEBUG: "1"
      FLASK_ENV: "development"
      FLASK_APP: "/mindsdb/mindsdb/__main__.py"
      SEPARATE_MIGRATIONS: "1"
    depends_on:
      - mindsdb-migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:47334/api/util/ping"]
      interval: 30s
      timeout: 4s
      retries: 100

  ml-service:
    image: mindsdb/ml_service:latest
    depends_on:
      - mindsdb-core
      - db-service
    environment:
      PORT: 5001
      MINDSDB_STORAGE_DIR: "${MINDSDB_STORAGE_DIR:/storage/var}"
      MINDSDB_DB_SERVICE_HOST: "db-service"
      MINDSDB_DB_SERVICE_PORT: 5000

  db-service:
    image: mindsdb/db_service:latest
    depends_on:
      - mindsdb-core
    environment:
      PORT: 5000
      MINDSDB_STORAGE_DIR: "${MINDSDB_STORAGE_DIR:/storage/var}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 120s
      timeout: 4s
      retries: 100

  executor-service:
    image: mindsdb/executor:latest
    depends_on:
      - mindsdb-core
      - ml-service
      -
