name: MindsDB Code Checks

on:
  pull_request:
    branches: [stable, staging]
    
jobs:
  prepare-matrix:
    name: Prepare Matrix Output
    runs-on: ubuntu-latest
    outputs: 
      python-versions: ${{ steps.step1.outputs.matrix }}
    steps: 
      - name: Create Matrix Variable
        id: step1
        run: echo matrix=${{vars.CI_TEST_PYTHON_VERSIONS}} >> $GITHUB_OUTPUT

  check_requirements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: ${{ vars.CI_PYTHON_VERSION }}
    - name: Check main requirements
      shell: bash
      run: |
        # We don't need to install mindsdb itself here because these are just static code checks
        pip install -r requirements/requirements-dev.txt

        python tests/scripts/check_requirements.py

  check_install:
    runs-on: ubuntu-latest
    needs: [prepare-matrix]
    strategy: 
      matrix: 
        python-version: ${{ fromJSON(needs.prepare-matrix.outputs.python-versions) }}
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check requirements files are installable
      shell: bash
      run: |
        pip install --dry-run --ignore-installed . # Install only the default handlers. We can expand this to all handlers later with: .[all_handlers_extras]
