name: MindsDB Static Code Checking

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  code_checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install flake8
      run: |
        pip install flake8==5.0.4 pycodestyle==2.9.1
      shell: bash
    - run: |
        python3 -m flake8
      shell: bash
    - name: Static code checking
      if: failure()
      run: |-
        curl \
          -X POST \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GH_ACCESS_KEY }}" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/${{ github.run_id }}/cancel"
